spring:
  application:
    # Spring自己的键,配置时忽略即可
    name: QMsgBackend
    # 服务器名称
    server-name: Qby Messenger
    # AES/ECB/PKCS5 Key 长度必须为16
    # 实际部署请修改此值
    crypt-key: powered-by-zzyss
    # 上传文件的保存目录 使用~代替用户根目录
    # 只要服务端有权限访问就可以 通常不需要手动干涉
    upload:
      dir: ~/.cubewhy/messenger/backend
      # 密钥失效时间 单位second
      keyExpire: 600
    register:
      # 是否允许直接注册
      state: true
    push:
      fcm:
        # 是否启用Firebase推送
        # 禁用后只使用Websocket
        state: false
        # 配置文件地址
        # 不要分享你的配置文件
        # 注意: 即使禁用了Firebase推送,你也需要一个配置文件
        config: ~/.cubewhy/messenger/fcm.json
    motd:
      # 是否显示Motd
      state: true
      # 题目
      title: Welcome to QMessenger
      # 具体内容 (点击后显示)
      text: An opensource fullstack chat application, designed with Love ♥️
  kafka:
    bootstrap-servers: localhost:9092
  security:
    jwt:
      # 实际部署请修改这个
      key: zzyss-please-mod-this
      expire: 7
  datasource:
    # 如果需要其他数据库需要在build.gradle.kts中添加对应的lib并重新编译
    url: jdbc:h2:file:./qmsgdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis
    redis:
      time-to-live: 5s