spring:
  application:
    name: QMsgBackend
    # AES/ECB/PKCS5 Key 长度必须为16
    # 实际部署请修改此值
    crypt-key: powered-by-zzyss
  kafka:
    bootstrap-servers: localhost:9092
  security:
    jwt:
      # 实际部署请修改这个
      key: zzyss-please-mod-this
      expire: 7
  datasource:
    url: jdbc:h2:file:./qmsgdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      time-to-live: 5s